id: P99AA4CAA
initial_creation_type: input
source_metadata:
  title: Khenpo Yönten Gönpo Series
  language: en
  description: Khenpo Yönten Gönpo (yon tan mgon po), or Jigme Tamdrin Yönten Gönpo
    ('jigs med rta mgrin yon tan mgon po, 1899–1959) was an important khenpo of Dzogchen
    Monastery and one of the main disciples of Khenpo Shenga.
  volume:
    3f1c34b106e9468ab0abf6491c006d2c:
      title: 'The Lion''s Roar of Definitive Meaning: A Difficult Point Concerning
        Samaya'
      parent: Advice
created_at: '2022-03-01T00:30:16.072539'
last_modified_at: '2022-03-01T00:30:16.072545'
